[package]
name = "pc80-emu"
version = "0.1.0"
authors = ["amberisvibin"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rz80 = "0.1"

[[bin]]
name = "pc80-emu"
path = "main.rs"
